/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ModeloDAO.AdministrarSolicitudes_adminDAO;
import ModeloVO.AdministrarSolicitudes_adminVO;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 57305
 */
public class AdministrarSolicitudesEM_admin extends javax.swing.JFrame {

    AdministrarSolicitudes_adminVO asVO = new AdministrarSolicitudes_adminVO();
    AdministrarSolicitudes_adminDAO asDAO = new AdministrarSolicitudes_adminDAO();
    ArrayList<AdministrarSolicitudes_adminVO> listaSinFiltro = new AdministrarSolicitudes_adminDAO().mostrarDatosSinFiltro();
    ArrayList<AdministrarSolicitudes_adminVO> listaConFiltro = new AdministrarSolicitudes_adminDAO().mostrarDatosConFiltro();

    /**
     * Creates new form AdministrarSolicitudesEM_admin
     */
    public AdministrarSolicitudesEM_admin() {
        initComponents();
        this.mostrarSinFiltro();
        this.mostrarConFiltro();
    }

    public void mostrarSinFiltro() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Asset SN");
        modelo.addColumn("Asset Name");
        modelo.addColumn("Request Date");
        modelo.addColumn("Accountable Party");
        modelo.addColumn("Deapartment");
        //jTable_conFiltro.setModel(modelo);
        jTable_sinFiltro.setModel(modelo);
        String[] vector = new String[5];
        try {
            for (int i = 0; i < listaSinFiltro.size(); i++) {
                asVO = listaSinFiltro.get(i);
                vector[0] = asVO.getAssetSN();
                vector[1] = asVO.getAssetName();
                vector[2] = asVO.getReportDate();
                vector[3] = asVO.getFullNameEmployee();
                vector[4] = asVO.getDepartment();
                modelo.addRow(vector);
            }
        } catch (Exception e) {
            Logger.getLogger(AdministrarSolicitudesEM_admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public void mostrarConFiltro() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Asset SN");
        modelo.addColumn("Asset Name");
        modelo.addColumn("Request Date");
        modelo.addColumn("Accountable Party");
        modelo.addColumn("Deapartment");
        //jTable_conFiltro.setModel(modelo);
        jTable_conFiltro.setModel(modelo);
        String[] vector = new String[5];
        try {
            for (int i = 0; i < listaConFiltro.size(); i++) {
                asVO = listaConFiltro.get(i);
                vector[0] = asVO.getAssetSN();
                vector[1] = asVO.getAssetName();
                vector[2] = asVO.getReportDate();
                vector[3] = asVO.getFullNameEmployee();
                vector[4] = asVO.getDepartment();
                modelo.addRow(vector);
            }
        } catch (Exception e) {
            Logger.getLogger(AdministrarSolicitudesEM_admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_sinFiltro = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_conFiltro = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTable_sinFiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_sinFiltro);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(137, 137, 137))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jTable_conFiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_conFiltro);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int soloUna = jTable_sinFiltro.getSelectedRowCount();
        if (soloUna == 1) {
            int filaSeleccionada = jTable_sinFiltro.getSelectedRow();
            /*Object datos0 = jTable_sinFiltro.getValueAt(filaSeleccionada, 0);//assets sn
            Object datos1 = jTable_sinFiltro.getValueAt(filaSeleccionada, 1);//assets name
            Object datos2 = jTable_sinFiltro.getValueAt(filaSeleccionada, 2);//assets rdate
            Object datos3 = jTable_sinFiltro.getValueAt(filaSeleccionada, 3);//assets employee
            Object datos4 = jTable_sinFiltro.getValueAt(filaSeleccionada, 4);//assets department*/
            String data0 = String.valueOf(jTable_sinFiltro.getValueAt(filaSeleccionada, 0));
            String data1 = String.valueOf(jTable_sinFiltro.getValueAt(filaSeleccionada, 1));
            String data2 = String.valueOf(jTable_sinFiltro.getValueAt(filaSeleccionada, 2));
            String data3 = String.valueOf(jTable_sinFiltro.getValueAt(filaSeleccionada, 3));
            String data4 = String.valueOf(jTable_sinFiltro.getValueAt(filaSeleccionada, 4));
            AdministrarSolicitudes_adminVO numero1_VO = new AdministrarSolicitudes_adminVO();
            numero1_VO.setAssetSN(data0);
            numero1_VO.setAssetName(data1);
            numero1_VO.setReportDate(data2);
            numero1_VO.setFullNameEmployee(data3);
            numero1_VO.setDepartment(data4);
            //EMRQ01 pantalla = new EMRQ01(numero1_VO);
            //pantalla.setVisible(true);
            try {
                Emrq01 pantalla = new Emrq01(numero1_VO);
                pantalla.setVisible(true);
            } catch (Exception e) {
                System.out.println("error "+e);
            }
            
        } else {
            System.out.println("debe selccionar 1 fila cono max y como min");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarSolicitudesEM_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarSolicitudesEM_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarSolicitudesEM_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarSolicitudesEM_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarSolicitudesEM_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_conFiltro;
    private javax.swing.JTable jTable_sinFiltro;
    // End of variables declaration//GEN-END:variables
}
