/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.Empleado_Ctr;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modeloDAO.EmpleadoDAO;
import modeloVO.EmpleadoVO;

/**
 *
 * @author 57305
 */
public class ModificarEmpleado extends javax.swing.JFrame {

    private String id = "", firstName = "", lastName = "", phone = "", isAdmin = "", userName = "", password = "";
    EmpleadoVO empleadoVO = new EmpleadoVO();
    EmpleadoDAO empleadoDAO = new EmpleadoDAO();
    ArrayList<EmpleadoVO> lista = new EmpleadoDAO().mostrarEmpleados();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form RegistrarEmpleado
     */
    public ModificarEmpleado() {
        initComponents();
        modelo.addColumn("id");
        modelo.addColumn("FirstName");
        modelo.addColumn("LastName");
        modelo.addColumn("Phone");
        modelo.addColumn("IsAdmin");
        modelo.addColumn("Username");
        modelo.addColumn("Password");
        jTable_tados.setModel(modelo);
        this.mostrar();
    }

    public void mostrar() {
        String[] vector = new String[7];
        try {
            for (int i = 0; i < lista.size(); i++) {
                empleadoVO = lista.get(i);
                vector[0] = empleadoVO.getId();
                vector[1] = empleadoVO.getFirstName();
                vector[2] = empleadoVO.getLastName();
                vector[3] = empleadoVO.getPhone();
                vector[4] = empleadoVO.getIsAdmin();
                vector[5] = empleadoVO.getUserName();
                vector[6] = empleadoVO.getPassword();
                modelo.addRow(vector);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox_isadmin = new javax.swing.JCheckBox();
        jTextField_password = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jTextField_phone = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jTextField_lastname = new javax.swing.JTextField();
        jButton_modificarEmpleado = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel_id = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modify Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("FirstName: ");
        jLabel5.setToolTipText("FirstName");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("LastName: ");
        jLabel6.setToolTipText("FirstName");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Phone:");
        jLabel4.setToolTipText("FirstName");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Username: ");
        jLabel8.setToolTipText("FirstName");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password: ");
        jLabel7.setToolTipText("FirstName");

        jCheckBox_isadmin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox_isadmin.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox_isadmin.setText("Is Admin");
        jCheckBox_isadmin.setOpaque(false);
        jCheckBox_isadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_isadminActionPerformed(evt);
            }
        });

        jTextField_password.setOpaque(false);

        jTextField_username.setOpaque(false);

        jTextField_phone.setOpaque(false);

        jTextField_name.setOpaque(false);

        jTextField_lastname.setOpaque(false);

        jButton_modificarEmpleado.setBackground(new java.awt.Color(0, 255, 0));
        jButton_modificarEmpleado.setText("MODIFY");
        jButton_modificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificarEmpleadoActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel_id.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Id:");
        jLabel9.setToolTipText("FirstName");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel_id, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox_isadmin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_modificarEmpleado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel_id, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_modificarEmpleado)
                        .addComponent(jButton2)
                        .addComponent(jCheckBox_isadmin)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTable_tados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_tados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_tados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_isadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_isadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_isadminActionPerformed

    private void jButton_modificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modificarEmpleadoActionPerformed
        this.id = String.valueOf(jLabel_id.getText());
        this.firstName =String.valueOf(jTextField_name.getText()) ;
        this.lastName = String.valueOf(jTextField_lastname.getText()) ;
        this.phone = String.valueOf(jTextField_phone.getText()) ;
        if (jCheckBox_isadmin.isSelected()) {
            isAdmin = "1";
        } else {
            isAdmin = "0";
        }
        //this.isAdmin = String.valueOf(jCheckBox_isadmin) ;
        this.userName = String.valueOf(jTextField_username.getText()) ;
        this.password = String.valueOf(jTextField_password.getText()) ;
        EmpleadoVO empleado_VO = new EmpleadoVO(id, firstName, lastName, phone, isAdmin, userName, password);
        EmpleadoDAO empleado_DAO = new EmpleadoDAO(empleado_VO);
        empleado_DAO.modificarEmpleado();
        GestionUsuarios pantalla = new GestionUsuarios();
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_modificarEmpleadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GestionUsuarios pantalla = new GestionUsuarios();
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable_tadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tadosMouseClicked
        jCheckBox_isadmin.setSelected(false);
        int empleadoSeleccionado = jTable_tados.rowAtPoint(evt.getPoint());
        jLabel_id.setText(String.valueOf(jTable_tados.getValueAt(empleadoSeleccionado, 0)));
        jTextField_name.setText(String.valueOf(jTable_tados.getValueAt(empleadoSeleccionado, 1)));
        jTextField_lastname.setText(String.valueOf(jTable_tados.getValueAt(empleadoSeleccionado, 2)));
        jTextField_phone.setText(String.valueOf(jTable_tados.getValueAt(empleadoSeleccionado, 3)));
        /*String valorIsAdmin = String.valueOf(jTable_tados.getValueAt(empleadoSeleccionado, 4));
        int valorIntIsAdmin = Integer.valueOf(valorIsAdmin);
        if (valorIntIsAdmin == 1) {
            jCheckBox_isadmin.setSelected(true);
        }*/
        if (jTable_tados.getValueAt(empleadoSeleccionado,4) == null) {
            jCheckBox_isadmin.setSelected(false);
            jCheckBox_isadmin.setText("is Admin: not selected");
        }else{
            String valorIsAdmin = String.valueOf(jTable_tados.getValueAt(empleadoSeleccionado, 4));
            int valorIntIsAdmin = Integer.valueOf(valorIsAdmin);
            if (valorIntIsAdmin == 1) {
                jCheckBox_isadmin.setSelected(true);
                jCheckBox_isadmin.setText("is Admin: selected");
            }else{
                jCheckBox_isadmin.setSelected(false);
                jCheckBox_isadmin.setText("is Admin: not selected");
            }
        }
        //jCheckBox_isadmin.setText(String.valueOf(jTable_tados.getValueAt(empleadoSeleccionado,4)));
        jTextField_username.setText(String.valueOf(jTable_tados.getValueAt(empleadoSeleccionado, 5)));
        jTextField_password.setText(String.valueOf(jTable_tados.getValueAt(empleadoSeleccionado, 6)));

    }//GEN-LAST:event_jTable_tadosMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_modificarEmpleado;
    private javax.swing.JCheckBox jCheckBox_isadmin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_tados;
    private javax.swing.JTextField jTextField_lastname;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
